---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # Markdown lint
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
        args: [-t, ~line_length]
  # Add trailing commas to calls and literals.
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  # Docker lint
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
      - id: docker-compose-check
  # Type checks
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args: [--config-file=./.github/linters/.mypy.ini]
  # Upgrade syntax for newer versions of the language
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
  # Sort imports
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile=black]
  # Format Python docstrings
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.6.2
    hooks:
      - id: pydocstringformatter
  # Code styling
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  # Remove unused imports and variables
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --remove-unused-variables,
          ]
  # PEP 8 style guide, error and complexity checks
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config=./.github/linters/.flake8]
  # Security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--skip=B101]

  # Local hooks
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        types: [python]
        entry: ./env/bin/pylint
        args: [--rcfile=.pylintrc]
