version: '3.9'

services:
  app:
    build: ./app
    # restart: always
    # ports:
      # - "8080:8080"
    # volumes:
    #   - type: bind
    #   source: ./data
    #   target: /data
    # command: