---
version: '3.9'

services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /usr/local/app
    command: python main.py